# Site settings
title: DyMoDiF
email: barunik@utia.cas.cz
url: "http://barunik.github.io"
description: "Dynamic Models for the Digital Finance <br/> GACR EXPRO GX19-28231X project <br/> (2019 - 2023)"
baseurl: "/dymodif"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Jozef Barunik

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
